feature(REPORT-333381): Bold-Reports 5.3 Release Changes
boldreports/aspnet-mvc-samples pull request #29
Opened 2023-10-30 07:08 UTC by SundaresanGunasekaran

<table>
<tr>
<td>
Description:
</td>
<td>
Bold-Reports 5.3 Release Changes
</td>
</tr>
<tr>
<td>
Analysis:
</td>
<td>
Analyzed about release changes
</td>
</tr>
<tr>
<td>
Reason for not identifying earlier:
</td>
<td>
It's a new feature
</td>
</tr>
<tr>
<td>
Is it a breaking issue?
</td>
<td>
No, It's a new feature
</td>
</tr>
<tr>
<td>
Solution description:
</td>
<td>
Bold-Reports 5.3 Release Changes
</td>
</tr>
<tr>
<td>
Areas affected and ensured:
</td>
<td>
NA
</td>
</tr>
<tr>
<td>
Test cases:
</td>
<td>
NA
</td>
</tr>
<tr>
<td>
Test bed sample location:
</td>
<td>
VS & VS Code
</td>
</tr>
</table>

2023-11-06 05:59 UTC, karthickthangasamy requested changes

2023-11-06 05:59 UTC, karthickthangasamy commented on Scripts/bold-reports/v2.0/localization/l10n/ej.localetexts.ar-AE.min.js
Do we need the localization scripts for sample browsers?

2023-11-06 11:34 UTC, SundaresanGunasekaran commented on Scripts/bold-reports/v2.0/localization/l10n/ej.localetexts.ar-AE.min.js
@karthickthangasamy - we need default localization en-US files only, so I have removed the other locale files

2023-11-07 11:45 UTC, karthickthangasamy approved these changes

2023-11-07 11:45 UTC, merged